branches:
  except:
    - /^[0-9]/

language: cpp

cache:
  - apt

update-alternatives:
  - install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
  - install /usr/bin/g++ g++ /usr/bin/g++-4.9 50

sources:
  - trusty

# What to install before the build
before_install:
  # Domoticz needs the full history to be able to calculate the version string
  - git fetch --unshallow
  # OpenZWave
  - git clone https://github.com/OpenZWave/open-zwave.git open-zwave-read-only


# Build matrix definition
# * One build
#   1. Linux armhf
matrix:
  include:
  # Linux armhf
  - os: linux
    compiler:
      - gcc
    env: TARGET_ARCHITECTURE=armhf
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - boost-latest
        packages:
          - gcc-4.9
          - g++-4.9
          - libboost1.55-all-dev
          - cmake
          - libsqlite3-dev
          - curl
          - libcurl4-openssl-dev
          - libusb-dev
          - zlib1g-dev
          - libssl-dev
          - libudev-dev
          - git
          - libdigest-sha-perl
    script:
      - (cd open-zwave-read-only; make)
      - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_PATH=open-zwave-read-only
      - make


# What to do with the build artifacts
# - Upload to the Domoticz file server
before_deploy:
  - tar czf domoticz_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz domoticz History.txt License.txt domoticz.sh server_cert.pem updatebeta updaterelease www/ scripts/ Config/
  - shasum -a 256 domoticz_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz > domoticz_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz.sha256sum
  - cp appversion.h.txt version_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.h
  - cp History.txt history_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.txt
deploy:
  skip_cleanup: true
  provider: script
  script: curl --ftp-ssl -T "{domoticz_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz,domoticz_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz.sha256sum,version_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.h,history_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.txt,History.txt}" -k -u "$FTP_USER:$FTP_PASSWORD" "ftp://$FTP_HOST/Pro/"
  on:
    branch: master
    repo: domoticz/domoticz
